### ISSUE TITLE
[Question] Azure Document Vault - Why in the project are using Azure Function?

### ISSUE THREAD

**Issue by tomaszprasolek** [madebygps/cloud-projects#2]
You want to just use Azure Function to generate download link with expiration date?
User click e.g. "Generate link" and that trigger Azure Function - that how you assumed it will work?

This can be done in the app, but in here you use Azure Function especially just to use it, right? :) 

```
5. Develop Expiration Logic with Azure Functions:
- Allow users to generate unique download URLs with set expiration dates.
- The function will store the URL, associated document reference, and expiration in Cosmos DB.
```

**Comment by madebygps** [comment]
I don't understand your question. Please clarify what you mean by "especially just to use it"?

**Comment by tomaszprasolek** [comment]
Why you put that logic in Azure Function? You can implement it in the web app.

**Comment by madebygps** [comment]
Are you aware of the purpose of this projects repo and that project specifically?

**Comment by tomaszprasolek** [comment]
I think I understand the purpose :) The purpose is show the idea for the apps that use Azure that are needed to pass AZ-204 exam

**Comment by madebygps** [comment]
Correct, so for projects based on the az204 certification, wouldn't it make sense to encourage to get hands on with azure functions?

**Comment by tomaszprasolek** [comment]
_Correct, so for projects based on the az204 certification, wouldn't it make sense to encourage to get hands on with azure functions?_

Yes, you are right :)  
I just wanted to know if this using of Azure Function is needed e.g. by project architecture or is just used to learn it, to use it in project :)
